### PR TITLE
feat: add storybook

### LINKED ISSUE #131: Allow full customization in the demo page
at embeds.every.org we're showing the demo of the `donate-button` but it only shows a few specific customizations; would be cool if we can just use something like Storybook with its knobs functionality to allow for everything to be customized in the demo, instead of just showing a few of them.

### PR DESCRIPTION
**Pull request by martinbianchi**
closes #131 

@osdiab I succesfully implemented storybook and create some stories for the Widget and the Generic Button. I do not have access to Vercel but maybe would be a nice idea to use storybook as a preview for the widget

### CODE REVIEW

**Comment by osdiab** [comment]
nice! yeah that's a great idea, we can add that in a separate PR.

**Review by osdiab — APPROVED** [review]
great start!

**Comment by osdiab** [comment]
looks like the build got messed up somehow on this PR. debugging.

**Comment by osdiab** [comment]
seems to be because storybook uses `html-webpack-plugin@4` but the preact app and our hacked together config uses `html-webpack-plugin@3`. fixing it. this is an argument for #75

**Comment by osdiab** [comment]
ugh looks like `preact-cli` only supports `@3` and `storybook` only supports `@4`, which are mutually incompatible and causing issues when building. might need to move the storybook to a separate subpackage to make it work.

**Comment by osdiab** [comment]
i'm gonna hold off on merging this for now because of the build errors

**Comment by osdiab** [comment]
created issue on `preact-cli` here https://github.com/preactjs/preact-cli/issues/1551

**Comment by martinbianchi** [comment]
@osdiab I checked on my local environment and everything was working fine until I updated the `html-webpack-plugin` version to the `4.5.2` as you said. So I downgraded the version to the `3.2.0` that it's the version that preact uses and both compilations are working, at least on my local env. Do you think that for the time being is possible solution to this problem?

**Comment by osdiab** [comment]
oh sweet - nice! let's merge it then!

**Pull request merged**
