### PR TITLE
TypeScript, xo for linting, ava for testing

### LINKED ISSUE #11: Switch to TypeScript?
Throwing this out since other Every.org code is all in TypeScript and a switch to it would be pretty simple for me to implement. Is P22 team open to that @jake-nz ?

### LINKED ISSUE #17: Linting
Suggestion: add `prettier` and `ESLint` and enforce an out-of-box, autofixable coding style; can reuse the same ESLint rules we set for the rest of Every.org code (or use `xo`, but ESLint is fine IMO)

### PR DESCRIPTION
**Pull request by osdiab**
- move preact code to subpackage, monorepo structure using yarn workspaces
- switch to typescript, type everything
  - follow up: validate input arguments into publicly exposed functions
- xo for linting
- ava for testing
  - [x] todo: it's failing due to transpilation issues - fixed by pinning preact-cli version
- [x] todo: build script should copy built files in subpackage docs directory to root

Current challenge: HTMLWebpackPlugin seems to not work, maybe because I upgraded preact-cli. it looks like there are two HTML webpack plugin instances so how we override appears to be broken. Not totally sure how to debug (cc @jake-nz ), related #75 , will try to revert the preact-cli bump

once that works then can do more thorough testing

closes #11 
closes #17 
part of #16

### CODE REVIEW

**Review by jake-nz — APPROVED** [review]
Awesome! So good to get these things set up :)

**Comment by osdiab** [comment]
a lot of follow ups from this now that i've thoroughly spelunked the code, to improve its stability!

**Comment by osdiab** [comment]
tests still failing, ill figure it out in a later PR

**Comment by osdiab** [comment]
seems it thinks the docs needs updating since the preact config now results in my local directories being included in the sourcemap paths. that's odd

**Comment by osdiab** [comment]
im just gonna land this for now since it's a net benefit, and deal with the script issues after

**Pull request merged**
